// <auto-generated />
using System;
using HerbioMart.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HerbioMart.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910111517_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HerbioMart.Models.Entities.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiseaseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DiseaseId");

                    b.ToTable("Diseases");

                    b.HasData(
                        new
                        {
                            DiseaseId = 1,
                            Description = "Chronic high blood pressure condition requiring vascular relaxation.",
                            DiseaseName = "Hypertension",
                            Symptoms = "Headache, Dizziness, Shortness of breath"
                        },
                        new
                        {
                            DiseaseId = 2,
                            Description = "Metabolic condition characterized by elevated blood glucose levels.",
                            DiseaseName = "Type 2 Diabetes",
                            Symptoms = "Excessive thirst, Frequent urination, Fatigue"
                        },
                        new
                        {
                            DiseaseId = 3,
                            Description = "Chronic inflammation of the airways causing breathing difficulty.",
                            DiseaseName = "Asthma & Bronchitis",
                            Symptoms = "Wheezing, Coughing, Chest tightness"
                        },
                        new
                        {
                            DiseaseId = 4,
                            Description = "Functional gastrointestinal conditions affecting digestion and colon comfort.",
                            DiseaseName = "Digestive Disorders (IBS)",
                            Symptoms = "Bloating, Abdominal cramps, Indigestion"
                        },
                        new
                        {
                            DiseaseId = 5,
                            Description = "Sleep disruption and elevated psychological stress levels.",
                            DiseaseName = "Insomnia & Anxiety",
                            Symptoms = "Difficulty falling asleep, Restlessness, Chronic fatigue"
                        });
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("RatingValue")
                        .HasColumnType("float");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Herb", b =>
                {
                    b.Property<int>("HerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbId"));

                    b.Property<int?>("AddedByHerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HerbName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HerbId");

                    b.HasIndex("AddedByHerbalistId");

                    b.ToTable("Herbs");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Herbalist", b =>
                {
                    b.Property<int>("HerbalistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HerbalistId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HerbalistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Herbalists");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.HerbalistHerb", b =>
                {
                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HerbalistId", "HerbId");

                    b.HasIndex("HerbId");

                    b.ToTable("HerbalistHerbs");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryId"));

                    b.Property<bool>("Asthma")
                        .HasColumnType("bit");

                    b.Property<bool>("Diabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("Hypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("KidneyDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("LiverDisease")
                        .HasColumnType("bit");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("Smoker")
                        .HasColumnType("bit");

                    b.HasKey("MedicalHistoryId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ItemsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("PatientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.OrderHerb", b =>
                {
                    b.Property<int>("OrderHerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderHerbId"));

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderHerbId");

                    b.HasIndex("HerbId");

                    b.HasIndex("SubOrderId");

                    b.ToTable("OrderHerbs");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.OrderRecipe", b =>
                {
                    b.Property<int>("OrderRecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderRecipeId"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("SubOrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderRecipeId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("SubOrderId");

                    b.ToTable("OrderRecipes");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PatientId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("HerbalistId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.RecipeDisease", b =>
                {
                    b.Property<int>("RecipeDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeDiseaseId"));

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeDiseaseId");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeDiseases");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.RecipeHerb", b =>
                {
                    b.Property<int>("RecipeHerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeHerbId"));

                    b.Property<int>("HerbId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("RecipeHerbId");

                    b.HasIndex("HerbId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeHerbs");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.SubOrder", b =>
                {
                    b.Property<int>("SubOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubOrderId"));

                    b.Property<int>("HerbalistId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SubOrderId");

                    b.HasIndex("HerbalistId");

                    b.HasIndex("OrderId");

                    b.ToTable("SubOrders");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Feedback", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.Recipe", "Recipe")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Herb", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Herbalist", "AddedByHerbalist")
                        .WithMany("AddedHerbs")
                        .HasForeignKey("AddedByHerbalistId");

                    b.Navigation("AddedByHerbalist");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Herbalist", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.User", "User")
                        .WithOne("Herbalist")
                        .HasForeignKey("HerbioMart.Models.Entities.Herbalist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.HerbalistHerb", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Herb", "Herb")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.Herbalist", "Herbalist")
                        .WithMany("HerbalistHerbs")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.MedicalHistory", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Patient", "Patient")
                        .WithOne("MedicalHistory")
                        .HasForeignKey("HerbioMart.Models.Entities.MedicalHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Order", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Patient", "Patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.OrderHerb", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Herb", "Herb")
                        .WithMany("OrderHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderHerbs")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.OrderRecipe", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Recipe", "Recipe")
                        .WithMany("OrderRecipes")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.SubOrder", "SubOrder")
                        .WithMany("OrderRecipes")
                        .HasForeignKey("SubOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("SubOrder");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Patient", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("HerbioMart.Models.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Recipe", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Herbalist", "Herbalist")
                        .WithMany("Recipes")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Herbalist");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.RecipeDisease", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Disease", "Disease")
                        .WithMany("RecipeDiseases")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.Recipe", "Recipe")
                        .WithMany("RecipeDiseases")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.RecipeHerb", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Herb", "Herb")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("HerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.Recipe", "Recipe")
                        .WithMany("RecipeHerbs")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herb");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.SubOrder", b =>
                {
                    b.HasOne("HerbioMart.Models.Entities.Herbalist", "Herbalist")
                        .WithMany("SubOrders")
                        .HasForeignKey("HerbalistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HerbioMart.Models.Entities.Order", "Order")
                        .WithMany("SubOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Herbalist");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Disease", b =>
                {
                    b.Navigation("RecipeDiseases");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Herb", b =>
                {
                    b.Navigation("HerbalistHerbs");

                    b.Navigation("OrderHerbs");

                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Herbalist", b =>
                {
                    b.Navigation("AddedHerbs");

                    b.Navigation("HerbalistHerbs");

                    b.Navigation("Recipes");

                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Order", b =>
                {
                    b.Navigation("SubOrders");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Patient", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("MedicalHistory");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.Recipe", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("OrderRecipes");

                    b.Navigation("RecipeDiseases");

                    b.Navigation("RecipeHerbs");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.SubOrder", b =>
                {
                    b.Navigation("OrderHerbs");

                    b.Navigation("OrderRecipes");
                });

            modelBuilder.Entity("HerbioMart.Models.Entities.User", b =>
                {
                    b.Navigation("Herbalist");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
